// Assign the comprehensive Metrored tariff to a global variable so that
// DataStore can seed localStorage with the full price list on first load.
window.SSOTariff = [
  { name: "1 SESION FISIOTERAPIA", cost: 22.05 },
  { name: "1 SESION FISIOTERAPIA A DOMICILIO", cost: 28.0 },
  { name: "1 SESION TERAPIA ONDAS DE CHOQUE", cost: 60.0 },
  { name: "1 SESION TERAPIA SUELO PELVICO", cost: 46.0 },
  { name: "17 HIDROXI-PROGESTERONA", cost: 17.0 },
  { name: "17-BETA ESTRADIOL", cost: 16.04 },
  { name: "AC ANTI NMDA -NMETIL-D-ASPARTATO RECEPTOR", cost: 428.4 },
  { name: "AC ANTICARDIOLIPINA", cost: 156.48 },
  { name: "AC ANTICELUL. PARIETALES GAST.", cost: 86.9 },
  { name: "AC. ANTI ENDOMISIO IGA", cost: 45.48 },
  { name: "AC. ANTI. ENDOMISIO IGG", cost: 45.48 },
  { name: "AC. ANTIFOSFATIDIL SERINA IGG-IGM-IGA", cost: 130.91 },
  { name: "AC. ANTINEUTROFILOS -ANCA (MPO-PR3)", cost: 188.3 },
  { name: "AC. ANTINUCLEOSOMA", cost: 49.61 },
  { name: "AC. ANTITRANSGLUTAMINASA IGA", cost: 64.28 },
  { name: "AC. ANTITRANSGLUTAMINASA IGG", cost: 64.28 },
  { name: "AC. ATPO (PEROXIDASA)", cost: 38.79 },
  { name: "ACIDO 5 HIDROXI-INDOLACETICO", cost: 42.0 },
  { name: "ACIDO FOLICO SERICO", cost: 68.18 },
  { name: "ACIDO LACTICO", cost: 54.26 },
  { name: "ACIDO URICO", cost: 7.31 },
  { name: "ACIDO URICO EN ORINA DE 24H", cost: 7.31 },
  { name: "ACIDO URICO EN ORINA PARCIAL", cost: 7.31 },
  { name: "ACIDO VALPROICO", cost: 32.41 },
  { name: "ACLARAMIENTO-CREATININA", cost: 11.34 },
  { name: "ACTH", cost: 52.92 },
  { name: "ADENOVIRUS", cost: 26.87 },
  { name: "ADM. MEDICACION PARENTERAL", cost: 18.77 },
  { name: "AGLUTINACIONES FEBRILES", cost: 11.92 },
  { name: "ALBUMINA", cost: 7.14 },
  { name: "ALCOHOL SERICO", cost: 36.94 },
  { name: "ALDOLASA", cost: 13.2 },
  { name: "ALDOSTERONA", cost: 25.2 },
  { name: "ALERGENO ACIDO BENZOICO (C703). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO BROCOLI (F260). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO CANGREJO DE MAR (F23). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO CEBOLLA (F48). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO CLARA DE HUEVO IGE", cost: 20.4 },
  { name: "ALERGENO COLIFLOR (F291). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO DERMATOPHAGOIDES FARINAE IGE", cost: 20.4 },
  { name: "ALERGENO DERMATOPHAGOIDES PTERONISSINUS NDER P1 (D202) ACAROS. ANTICUE IGE", cost: 64.0 },
  { name: "ALERGENO DERMATOPHAGOIDES PTERONYSSINUS IGE", cost: 20.4 },
  { name: "ALERGENO EPITELIO - CASPA DE GATO IGE", cost: 20.4 },
  { name: "ALERGENO FRIJOL BLANCO (F15). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO HUEVO (F245). ANTICUE IGE", cost: 19.44 },
  { name: "ALERGENO LECHE DE VACA IGE", cost: 20.4 },
  { name: "ALERGENO LECHE HERVIDA IGE", cost: 20.4 },
  { name: "ALERGENO LENTEJA (F235). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO LEVADURA (PANADERIA / CERVECERIA) (F45). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO MANI, ANTICUERPOS IGE", cost: 20.4 },
  { name: "ALERGENO MULTIPLE EX2 (E1. E5. E6. E87. E88) (CASPA GATO. CASPA PERRO. COBAYA RATA RATON) EPITELIOS", cost: 96.0 },
  { name: "ALERGENO MULTIPLE FX1 (F13.F17.F18.F20.F36) (CACAHUETE. AVELLANA. NUEZ DE BRASIL. ALMENDRA. COCO)", cost: 96.0 },
  { name: "ALERGENO MULTIPLE FX16 (F44. F94. F208. F210) (FRESA. PERA. LIMON. PINA) FRUTAS. ANTICUE IGE", cost: 96.0 },
  { name: "ALERGENO MULTIPLE FX2 (F3. F24. F37. F40. F41) (BACALAO. GAMBA. MEJILLON. ATUN. SALMON) ALIMENTOS", cost: 96.0 },
  { name: "ALERGENO MULTIPLE FX21 (F84. F87. F92. F95. F210) (KIWI. MELON. PLATANO. MELOCOTON. PINA)  ALIMENTOS", cost: 96.0 },
  { name: "ALERGENO MULTIPLE FX26 (F1 F2 F13 F17) (CLARA DE HUEVO.  LECHE DE VACA CACAHUETE MOSTAZA) ALIMENTOS", cost: 96.0 },
  { name: "ALERGENO MULTIPLE GX2 (G2. G5. G6. G8 G10 G17) GRAMA MAYOR BALLICO HIERBA TIMOTEA. ESPIGUILLA. SORGO", cost: 96.0 },
  { name: "ALERGENO MULTIPLE MX1 (M1.M2.M3.M6) PENICILLIUM NOTATUM. CLADOSPORIUM HERBARUM. ASPERGILLUS FUMIGATE", cost: 96.0 },
  { name: "ALERGENO MULTIPLE RX2 (D2. E1. E3. E5. M6) (DERMATOPHAGOIDES FARINAE. CASPA DE GATO. CASPA CABALLO.", cost: 96.0 },
  { name: "ALERGENO NARANJA (F33). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO OSTRA (F290). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO OVOMUCOIDE (F233). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO PESCADO / RAPE (F361) ALIMENTOS. ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO REPOLLO (F216). ANTICUE IGE", cost: 34.0 },
  { name: "ALERGENO SARDINA (PILCHARD) (F308). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO SUERO DE LECHE DE VACA (F236) ALIMENTOS. ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO SULFITO SODICO (C712). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO TRUCHA (F204). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO VITAMINA B12 (C721). ANTICUE IGE", cost: 24.0 },
  { name: "ALERGENO ZEA MAYS (G202) POLENES GRAMINEAS. ANTICUE IGE", cost: 24.0 },
  { name: "ALFA 1 ANTITRIPSINA EN SUERO", cost: 19.5 },
  { name: "ALFA FETO PROTEINA -AFP", cost: 31.32 },
  { name: "ALT -SGPT", cost: 9.58 },
  { name: "AMILASA", cost: 11.56 },
  { name: "AMILASA EN ORINA", cost: 11.56 },
  { name: "AMONIO", cost: 61.36 },
  { name: "ANA-BLOT", cost: 41.0 },
  { name: "ANALISIS DE PATERNIDAD/MATERNIDAD (SUPUESTO HIJO)", cost: 220.83 },
  { name: "ANDROSTENEDIONA", cost: 47.34 },
  { name: "ANEXINA V :G-M", cost: 38.5 },
  { name: "ANGIOTAC AORTA ABDOMINAL", cost: 385.84 },
  { name: "ANGIOTAC AORTA COMPLETA + MIEMBROS INFERIORES", cost: 642.86 },
  { name: "ANGIOTAC AORTA TORACO ABDOMINAL COMPLETA", cost: 715.0 },
  { name: "ANGIOTAC CEREBRAL", cost: 408.54 },
  { name: "ANGIOTAC CORONARIAS", cost: 446.43 },
  { name: "ANGIOTAC DE CUELLO", cost: 408.54 },
  { name: "ANGIOTAC MIEMBRO SUPERIOR", cost: 369.84 },
  { name: "ANGIOTAC MIEMBROS INFERIORES", cost: 535.71 },
  { name: "ANGIOTAC MIEMBROS SUPERIORES", cost: 578.76 },
  { name: "ANGIOTAC RENAL", cost: 369.84 },
  { name: "ANGIOTAC TORACICA", cost: 369.84 },
  { name: "ANOSCOPIA", cost: 40.0 },
  { name: "ANTI HAV  ANTICUERPOS TOTALES", cost: 37.11 },
  { name: "ANTI HAV - IGM", cost: 32.01 },
  { name: "ANTI HBC IGG (CORE)", cost: 32.01 },
  { name: "ANTI HBC IGM (CORE)", cost: 30.14 },
  { name: "ANTI HBS", cost: 52.35 },
  { name: "ANTI JO-1", cost: 26.65 },
  { name: "ANTI MULLERIANA (AMH)", cost: 81.91 },
  { name: "ANTIC. ANTI CITRULINA (CCP)", cost: 45.57 },
  { name: "ANTIC. ANTI VIMENTINA", cost: 47.72 },
  { name: "ANTIC. ANTI-DNA (CADENA SENCILLA)", cost: 47.22 },
  { name: "ANTIC. ANTI-DNA NATIVO (DOBLE CADENA)", cost: 21.15 },
  { name: "ANTIC. ANTI-NUCLEARES -ANA", cost: 60.46 },
  { name: "ANTIC.BETA 2GP1 : B2-GP1", cost: 43.05 },
  { name: "ANTICOAGULANTE LUPICO", cost: 96.05 },
  { name: "ANTICUE IGE ESPECIFICOS A -  (TRIGO. CENTENO. CEBADA. ARROZ) ALIMENTOS. SUERO", cost: 52.0 },
  { name: "ANTICUERPOS ANTI MITOCONDRIALE", cost: 78.15 },
  { name: "ANTICUERPOS ANTI SM-RNP", cost: 97.91 },
  { name: "ANTICUERPOS ANTI. CENTROMERO", cost: 78.15 },
  { name: "ANTICUERPOS ANTISSA- RO- SSB-LA", cost: 111.73 },
  { name: "ANTICUERPOS ANTI-TSH RECEPTOR", cost: 150.0 },
  { name: "ANTICUERPOS SARAMPION IGM", cost: 101.65 },
  { name: "ANTIG.CARCINO EMBRONARIO -CEA", cost: 30.62 },
  { name: "ANTIGENO AUSTRALIA HBS-AG", cost: 17.48 },
  { name: "ANTITROMBINA III", cost: 42.86 },
  { name: "APLICACION DE MEDICACION", cost: 15.0 },
  { name: "APOLIPOPROTEINA B", cost: 20.4 },
  { name: "ARTROCENTESIS", cost: 51.42 },
  { name: "ARTRORESONANCIA", cost: 455.0 },
  { name: "ASCA IGG- IGA", cost: 83.56 },
  { name: "AST - SGOT", cost: 9.58 },
  { name: "ASTO", cost: 10.89 },
  { name: "AUDIOMETRIA", cost: 32.14 },
  { name: "AZUCARES REDUCTORES EN HECES", cost: 4.85 },
  { name: "AZUCARES REDUCTORES EN ORINA", cost: 4.85 },
  { name: "BILIRRUBINAS", cost: 8.58 },
  { name: "BIOMETRIA HEMATICA", cost: 7.58 },
  { name: "BIOMETRIA HEMATICA+VSG", cost: 10.38 },
  { name: "BIOPSIA DE CERVIX", cost: 30.0 },
  { name: "BIOPSIA DE PIEL, TEJIDO CELULAR SUBCUTANEO Y/O MEMBRANA MUCOSA.", cost: 29.7 },
  { name: "BRUCELOSIS - HUDDLESON", cost: 6.42 },
  { name: "C3", cost: 29.28 },
  { name: "C4", cost: 24.66 },
  { name: "CA 15-3", cost: 51.56 },
  { name: "CA 19-9", cost: 49.13 },
  { name: "CA 72-4", cost: 29.25 },
  { name: "CA-125", cost: 38.2 },
  { name: "CADENAS LIGERAS LIBRES KAPPA Y LAMBDA EN ORINA", cost: 106.53 },
  { name: "CALCIO EN ORINA", cost: 8.58 },
  { name: "CALCIO EN ORINA DE 24 HORAS", cost: 8.58 },
  { name: "CALCIO IONICO EN SUERO", cost: 23.38 },
  { name: "CALCIO TOTAL", cost: 8.58 },
  { name: "CALCITONINA", cost: 26.4 },
  { name: "CALCULO RENAL", cost: 29.85 },
  { name: "CALPROTECTINA FECAL", cost: 138.0 },
  { name: "CARBAMACEPINA", cost: 32.69 },
  { name: "CARGA VIRAL PARA HIV-1", cost: 166.41 },
  { name: "CATECOLAMINAS DIFERENCIADAS EN ORINA DE 24 HORAS", cost: 42.0 },
  { name: "CATETERISMO VESICAL FOLEY", cost: 24.45 },
  { name: "CATETERISMO VESICAL NELATON", cost: 24.45 },
  { name: "CAUTERIZACION DE 1 - 5 ACROCORDONES", cost: 20.0 },
  { name: "CAUTERIZACION DE 10 - 15 ACROCORDONES", cost: 30.0 },
  { name: "CAUTERIZACION DE 5 - 10 ACROCORDONES", cost: 25.0 },
  { name: "CERULOPLASMINA", cost: 15.6 },
  { name: "CHLAMYDIA TRACHOMATIS IGG", cost: 37.61 },
  { name: "CHLAMYDIA TRACHOMATIS IGM", cost: 37.61 },
  { name: "CISTATINA C", cost: 63.95 },
  { name: "CITOLOGIA DE LIQUIDOS/PAT", cost: 58.4 },
  { name: "CITOLOGIA VAGINAL/PAT", cost: 18.0 },
  { name: "CITOMEGALOVIRUS ADN - PCR - CARGA VIRAL", cost: 178.61 },
  { name: "CITOMEGALOVIRUS IGG", cost: 33.71 },
  { name: "CITOMEGALOVIRUS IGM", cost: 35.62 },
  { name: "CITOQUIMICO L. SINOVIAL", cost: 51.83 },
  { name: "CK-MB", cost: 30.49 },
  { name: "CLORO EN ORINA", cost: 5.06 },
  { name: "CLORO EN ORINA DE 24 HORAS", cost: 5.06 },
  { name: "COBRE EN SUERO/PLASMA", cost: 24.0 },
  { name: "COLESTEROL", cost: 9.58 },
  { name: "COLINESTERASA SERICA", cost: 18.9 },
  { name: "COLOCACION DE INFUSION INTRAVENOSA", cost: 15.0 },
  { name: "COLOCACION DE VALVA DE YESO", cost: 17.13 },
  { name: "COLOCACION DE YESO", cost: 27.87 },
  { name: "COLONOSCOPIA", cost: 325.0 },
  { name: "COLPOSCOPIA + TOMA DE MUESTRA", cost: 105.33 },
  { name: "CONSULTA BASICA TELEMEDICINA", cost: 19.5 },
  { name: "CONSULTA MEDICA A DOMICILIO", cost: 20.0 },
  { name: "CONSULTA MEDICA BASICA", cost: 24.0 },
  { name: "CONSULTA MEDICA ESPECIALIDAD", cost: 33.0 },
  { name: "CONSULTA MEDICA PSICOLOGICA", cost: 35.0 },
  { name: "CONSULTA NUTRICION", cost: 24.0 },
  { name: "CONSULTA PSICOLOGIA TELEMEDICINA", cost: 24.0 },
  { name: "CONTAJE DE RETICULOCITOS", cost: 11.45 },
  { name: "COOMBS DIRECTO", cost: 9.31 },
  { name: "COOMBS INDIRECTO", cost: 14.26 },
  { name: "COPROPARASITARIO POR CONCENTRACION", cost: 6.35 },
  { name: "COPROPARASITARIO SERIADO X 2", cost: 8.88 },
  { name: "COPROPARASITARIO SERIADO X 3", cost: 11.12 },
  { name: "COPROPARASITARIO SIMPLE", cost: 3.38 },
  { name: "CORRECCION MANUAL DE FRACTURA", cost: 61.51 },
  { name: "CORTISOL", cost: 31.14 },
  { name: "CORTISOL AM-PM", cost: 41.86 },
  { name: "CORTISOL URINARIO", cost: 41.86 },
  { name: "CPK", cost: 16.81 },
  { name: "CREATININA", cost: 7.14 },
  { name: "CREATININA EN ORINA DE 24HORAS", cost: 7.14 },
  { name: "CREATININA EN ORINA PARCIAL", cost: 7.14 },
  { name: "CRIPTOSPORIDIUM", cost: 19.85 },
  { name: "CRISTALOGRAFIA", cost: 3.15 },
  { name: "CROMOGRANINA A", cost: 70.8 },
  { name: "C-TELOPEPTIDO (CROSSLAPS)", cost: 48.0 },
  { name: "CULTIVO DE ESTREPTOCOCO GRUP B", cost: 6.37 },
  { name: "CULTIVO DE HECES", cost: 33.97 },
  { name: "CULTIVO DE HONGOS", cost: 44.4 },
  { name: "CULTIVO DE SECRECION FARINGEA", cost: 17.98 },
  { name: "CULTIVO DE SECRECIONES Y OTROS", cost: 42.65 },
  { name: "CURACION HERIDA GRANDE", cost: 35.57 },
  { name: "CURACION HERIDA MEDIANA", cost: 24.84 },
  { name: "CURACION HERIDA PEQUENA", cost: 19.66 },
  { name: "CURACION SIMPLE", cost: 9.36 },
  { name: "CURVA DE GLUCOSA 2H", cost: 17.54 },
  { name: "CURVA DE GLUCOSA 3H EMBARAZO", cost: 17.54 },
  { name: "CURVA DE GLUCOSA 3HRS", cost: 17.54 },
  { name: "CURVA DE HIPOGLICEMIA 5H", cost: 25.13 },
  { name: "CURVA DE INSULINA 3HRS", cost: 137.9 },
  { name: "CURVA DE INSULINA 5 HORAS", cost: 163.61 },
  { name: "CURVA INSULINA 2 HRS", cost: 114.52 },
  { name: "CYFRA 21-1", cost: 32.68 },
  { name: "DEHIDROEPIANDROSTERONA -DHEAS", cost: 25.0 },
  { name: "DENSIDAD URINARIA", cost: 2.02 },
  { name: "DETECCION DE CHLAMYDIA TRACHOMATIS POR PCR", cost: 171.25 },
  { name: "DIGOXINA", cost: 33.78 },
  { name: "DIMERO-D", cost: 55.0 },
  { name: "DMO. ANTEBRAZO", cost: 11.86 },
  { name: "DMO. COLUMNA LATERAL", cost: 11.86 },
  { name: "DMO. COLUMNA LUMBAR A.P.", cost: 11.86 },
  { name: "DMO. COLUMNA Y FEMUR", cost: 21.85 },
  { name: "DMO. CUERPO TOTAL", cost: 19.83 },
  { name: "DMO.CUELLO DE FEMUR", cost: 11.86 },
  { name: "DRENAJE ABSCESO PEQUENO", cost: 21.24 },
  { name: "DRENAJE DE ABCESOS", cost: 225.0 },
  { name: "DRENAJE DE ABSCESO GRANDE", cost: 30.0 },
  { name: "DRENAJE DE ABSCESO MEDIANO", cost: 24.62 },
  { name: "DRENAJE DE CHALAZION", cost: 300.0 },
  { name: "D-XYLOSA", cost: 35.84 },
  { name: "E.B.V. AGUDO - VCA IGM", cost: 47.86 },
  { name: "E.B.V. EBNA IGG", cost: 46.57 },
  { name: "E.B.V. VCA IGG", cost: 46.57 },
  { name: "E.B.V.COMP VCAIGG- M EBNA IGG", cost: 119.37 },
  { name: "ECO ABDOMEN SUPERIOR", cost: 50.56 },
  { name: "ECO ABDOMEN TOTAL", cost: 50.56 },
  { name: "ECO AORTO ILIACO + MI BILATERAL", cost: 137.32 },
  { name: "ECO AORTO ILIACO + MI.INILAT.", cost: 114.49 },
  { name: "ECO CEREBRO DE RECIEN NAC", cost: 50.56 },
  { name: "ECO DE CADERAS", cost: 50.56 },
  { name: "ECO DE OJOS", cost: 50.56 },
  { name: "ECO DOPPLER AORTA ABDOMINAL Y ARTERIA ILIACA", cost: 114.49 },
  { name: "ECO DOPPLER RENAL", cost: 114.49 },
  { name: "ECO DOPPLER TESTICULAR", cost: 114.49 },
  { name: "ECO DOPPLER VENOSO BILATERAL", cost: 137.32 },
  { name: "ECO DOPPLER VENOSO UNILATERAL", cost: 114.49 },
  { name: "ECO DUPLEX CAROTIDEO", cost: 79.63 },
  { name: "ECO ENDOVAGINAL", cost: 50.56 },
  { name: "ECO MAMARIO", cost: 50.56 },
  { name: "ECO MONITOREO OVULATORIO", cost: 60.23 },
  { name: "ECO OBSTETRICO", cost: 50.56 },
  { name: "ECO OBSTETRICO + MARCADORES CROMOSOMICOS O CROMOSOMOPATIAS", cost: 100.0 },
  { name: "ECO OBSTETRICO 3D-4D", cost: 74.5 },
  { name: "ECO OBSTETRICO DOPPLER", cost: 114.49 },
  { name: "ECO OBSTETRICO PERFIL O DETALLE ANATOMICO", cost: 100.0 },
  { name: "ECO OSTEO-MUSCULAR", cost: 50.56 },
  { name: "ECO PARTES BLANDAS", cost: 50.56 },
  { name: "ECO PELVICO", cost: 50.56 },
  { name: "ECO RECTAL - PROSTATICO", cost: 50.56 },
  { name: "ECO RENAL", cost: 50.56 },
  { name: "ECO TESTICULAR", cost: 50.56 },
  { name: "ECO TIROIDES - PARATIROIDES", cost: 50.56 },
  { name: "ECOCARDIOGRAFIA", cost: 100.0 },
  { name: "EKG DE REPOSO I.C", cost: 25.36 },
  { name: "ELASTASA PANCREATICA", cost: 91.2 },
  { name: "ELECTROFORESIS DE HEMOGLOBINAS", cost: 35.0 },
  { name: "ELECTROFORESIS DE PROTEINAS", cost: 26.25 },
  { name: "ELECTROFORESIS DE PROTEINAS EN ORINA", cost: 53.0 },
  { name: "ELECTROLITOS NA- K - CL", cost: 5.06 },
  { name: "EMO - UROANALISIS DE RUTINA", cost: 6.56 },
  { name: "ENDOSCOPIA DIGESTIVA ALTA", cost: 295.0 },
  { name: "ENFERMEDAD DE LYME IGG E IGM", cost: 63.09 },
  { name: "EPSTEIN BAAR VIRUS-PCR/CARGA VIRAL", cost: 222.71 },
  { name: "ERGOMETRIA", cost: 106.11 },
  { name: "ERITROPOYETINA(EPO), NIVELES SERICOS", cost: 28.8 },
  { name: "ESCOPOLAMINA", cost: 90.33 },
  { name: "ESPERMATOGRAMA", cost: 27.0 },
  { name: "ESPIROMETRIA CON BRONCODIALTADOR", cost: 42.0 },
  { name: "ESPIROMETRIA SIMPLE I.C.", cost: 32.73 },
  { name: "ESTREPTOCOCO GRUPO A", cost: 27.8 },
  { name: "ESTRIOL LIBRE", cost: 63.53 },
  { name: "EXAMEN FRESCO", cost: 2.38 },
  { name: "EXAMEN GRAM", cost: 3.38 },
  { name: "EXAMEN KOH", cost: 3.38 },
  { name: "EXCISION DE LUNARES BENIGNOS:  TRONCO, ABDOMEN, EXTREMIDADES, DIAMETRO EXCISIONADO 0.5 CM O MENOS.", cost: 52.0 },
  { name: "EXCISION DE LUNARES BENIGNOS:  TRONCO, ABDOMEN, EXTREMIDADES, DIAMETRO EXCISIONADO 0.6 CM A 1.0 CM", cost: 61.36 },
  { name: "EXCISION DE NEVUS BENIGNOS: NUCA, MANOS, PIES, GENITALES, DIAMETRO EXCISIONADO  0.6 CM A 1.0 CM", cost: 61.36 },
  { name: "EXCISION DE NEVUS BENIGNOS: NUCA, MANOS, PIES, GENITALES, DIAMETRO EXCISIONADO 0.5 O MENOS.", cost: 52.0 },
  { name: "EXCISION DE OTROS NEVUS BENIGNOS : CARA, OIDOS, PARPADOS, NARIZ, MUCOSAS DIAMETRO  0.6 CM A 1.0 CM", cost: 81.36 },
  { name: "EXCISION DE OTROS NEVUS BENIGNOS : CARA, OIDOS, PARPADOS, NARIZ, MUCOSAS DIAMETRO 0.5 CM O MENOS MAS", cost: 72.0 },
  { name: "EXCISION, LESIONES MALIGNAS: CARA, OIDOS, PARPADOS, NARIZ, LABIOS, LESION DE DIAMETRO 0.5 CM O MENOS", cost: 90.9 },
  { name: "EXCISION, LESIONES MALIGNAS: CUERO CABELLUDO, NUCA, MANOS, PIES, GENITALES; DIAMETRO  0.6CM A 1.0CM", cost: 81.36 },
  { name: "EXCISION, LESIONES MALIGNAS: CUERO CABELLUDO, NUCA, MANOS, PIES, GENITALES; DIAMETRO 0.5 CM O MENOS", cost: 62.54 },
  { name: "EXCISION, LESIONES MALIGNAS:CARA, OIDOS, PARPADOS, NARIZ, LABIOS, LESION DE DIAMETRO 0.6CM A 1.0CM", cost: 91.54 },
  { name: "EXTRACCION CUERPO EXTRA\u00d1O GARGANTA", cost: 30.32 },
  { name: "EXTRACCION CUERPO EXTRA\u00d1O NARIZ", cost: 30.32 },
  { name: "EXTRACCION CUERPO EXTRA\u00d1O OIDO", cost: 30.32 },
  { name: "EXTRACCION DE CUERPO EXTRA\u00d1O CONJUNTIVAL SUPERFICIAL", cost: 30.32 },
  { name: "EXTRACCION DE LA U\u00d1A", cost: 34.22 },
  { name: "FACTOR II DE LA COAGULACI\u00d3N", cost: 123.0 },
  { name: "FACTOR INTRINSECO", cost: 56.42 },
  { name: "FACTOR REUMATOIDEO", cost: 9.9 },
  { name: "FACTOR V", cost: 17.9 },
  { name: "FACTOR V MUTACION (LEIDEN)", cost: 123.0 },
  { name: "FERRITINA", cost: 18.67 },
  { name: "FERULIZACION", cost: 160.0 },
  { name: "FIBRINOGENO", cost: 18.01 },
  { name: "FOSFATASA ACIDA TOTAL", cost: 13.39 },
  { name: "FOSFATASA-ACIDA-PROSTATICA", cost: 13.39 },
  { name: "FOSFATASA-ALKALINA", cost: 8.58 },
  { name: "FOSFORO", cost: 9.58 },
  { name: "FOSFORO EN ORINA", cost: 9.58 },
  { name: "FOSFORO EN ORINA DE 24 HORAS", cost: 9.58 },
  { name: "FRUCTOSAMINA", cost: 10.57 },
  { name: "FSH FOLICULO ESTIMULANTE", cost: 14.94 },
  { name: "FT3", cost: 10.29 },
  { name: "FT4", cost: 10.29 },
  { name: "FTA -ABS", cost: 21.62 },
  { name: "GAMMA GT (GGT)", cost: 8.24 },
  { name: "GASOMETRIA ARTERIAL", cost: 24.48 },
  { name: "GASOMETRIA VENOSA", cost: 24.48 },
  { name: "GIARDIA EN HECES", cost: 21.47 },
  { name: "GLUCOSA", cost: 5.33 },
  { name: "GLUCOSA 2H POSTPRANDIAL", cost: 5.33 },
  { name: "GLUCOSA 3H POSTPRANDIAL", cost: 5.33 },
  { name: "GLUCOSA BASAL Y 2 H POSTPRANDIAL", cost: 10.29 },
  { name: "GLUCOSA BASAL Y SOBRECARGA 2 H", cost: 12.27 },
  { name: "GLUCOSA EN ORINA", cost: 5.33 },
  { name: "GLUCOSA SOBRECARGA 2H - 1 TOMA", cost: 9.6 },
  { name: "GOTA FRESCA", cost: 3.15 },
  { name: "GRAM Y FRESCO", cost: 6.18 },
  { name: "GRASAS EN HECES - SUDAN III", cost: 7.69 },
  { name: "HAPTOGLOBINA", cost: 13.2 },
  { name: "HBE-ANTI HBE", cost: 52.86 },
  { name: "HCG BETA CUALITATIVA", cost: 17.66 },
  { name: "HCG BETA CUANTITATIVO", cost: 35.58 },
  { name: "HCO3", cost: 22.25 },
  { name: "HDL-LDL", cost: 17.6 },
  { name: "HE-4 : PROTEINA EPIDIMAL HUM-4", cost: 52.92 },
  { name: "HELICOBACTER PILORY IGG/IGA", cost: 34.09 },
  { name: "HELICOBACTER PYLORI EN HECES", cost: 16.36 },
  { name: "HEMATOCRITO HEMOGLOBINA", cost: 6.37 },
  { name: "HEMOCULTIVO POR 1 MUESTRA", cost: 58.4 },
  { name: "HEMOCULTIVO POR 3 MUESTRAS", cost: 111.29 },
  { name: "HEMOGLOBINA GLICOSILADA", cost: 16.61 },
  { name: "HEMOPARASITO + ANTIGENO", cost: 33.39 },
  { name: "HEPATITIS B, DNA CARGA VIRAL", cost: 108.0 },
  { name: "HEPATITIS C", cost: 29.86 },
  { name: "HEPATITIS C, RNA CARGA VIRAL", cost: 126.0 },
  { name: "HERPES I-IGG", cost: 24.07 },
  { name: "HERPES I-IGM", cost: 27.22 },
  { name: "HERPES II-IGG", cost: 24.07 },
  { name: "HERPES II-IGM", cost: 27.22 },
  { name: "HIERRO SERICO", cost: 7.3 },
  { name: "HIV COMBI 1+2+P24", cost: 20.22 },
  { name: "HLA B27,SSP (PCR)", cost: 51.6 },
  { name: "HOLTER EKG 24H", cost: 90.96 },
  { name: "HOLTER PA", cost: 90.96 },
  { name: "HOMOCISTEINA", cost: 66.29 },
  { name: "HORMONA DE CRECIMIENTO -HGH", cost: 29.44 },
  { name: "HPV - VIRUS PAPILOMA HUMANO", cost: 131.12 },
  { name: "HTLV l-ll lgG", cost: 82.27 },
  { name: "IGA", cost: 28.0 },
  { name: "IGE", cost: 20.2 },
  { name: "IGF-1 (SOMATOMEDINA C)", cost: 22.0 },
  { name: "IGG", cost: 28.0 },
  { name: "IGM", cost: 28.0 },
  { name: "IMPEDANCIOMETRIA", cost: 32.14 },
  { name: "INCISION DE HEMORROIDES TROMBOSAS EXTERNAS", cost: 225.0 },
  { name: "INDICE DE RIESGO PRENATAL SEGUNDO TRIMESTRE (AFP, BETA-HCG, ESTRIOL) TRIPLE TEST", cost: 117.97 },
  { name: "INDICE HOMA", cost: 31.27 },
  { name: "INFILTRACION", cost: 51.42 },
  { name: "INMUNOFIJACION-INMUNOTIPADO EN SUERO", cost: 74.02 },
  { name: "INMUNOGLOBULINAS IGA/IGG/IGM/IGE", cost: 83.36 },
  { name: "INMUNOHISTOQUIMICA P16", cost: 143.51 },
  { name: "INSULINA 2PP", cost: 25.94 },
  { name: "INSULINA BASAL Y POSPRANDIAL", cost: 48.0 },
  { name: "INSULINA BASAL Y SOBRECARGA 2H", cost: 48.0 },
  { name: "INSULINA LIBRE (BIOACTIVA)", cost: 51.5 },
  { name: "INTERLEUCINA 6- IL-6", cost: 64.28 },
  { name: "INV. DE EOSINOFILOS NASALES", cost: 3.38 },
  { name: "INV. DE OXIUROS", cost: 8.56 },
  { name: "LAVADO DE OIDOS", cost: 21.68 },
  { name: "LDH", cost: 9.58 },
  { name: "LEVETIRACETAN (KEPPRA), NIVELES SERICOS", cost: 91.2 },
  { name: "LH HORMONA LUTEINIZANTE", cost: 15.91 },
  { name: "LIGADURA DE HEMORROIDES INTERNA", cost: 175.0 },
  { name: "LIPASA", cost: 11.93 },
  { name: "LIPOPROTEINA A", cost: 33.63 },
  { name: "LITIO NIVELES SERICOS", cost: 14.4 },
  { name: "LKM1", cost: 23.89 },
  { name: "LOGOAUDIOMETRIA", cost: 32.14 },
  { name: "MAGNESIO", cost: 10.57 },
  { name: "MAGNESIO EN ORINA", cost: 10.57 },
  { name: "MAMOGRAFIA BILATERAL", cost: 35.71 },
  { name: "MAMOGRAFIA UNILATERAL", cost: 25.71 },
  { name: "MATRICECTOMIA CON FENOL -U\u00d1AS ENCARNADAS 1 LADO", cost: 121.28 },
  { name: "MICROALBUMINURIA EN ORINA PARCIAL", cost: 23.14 },
  { name: "MIOGLOBINA", cost: 34.59 },
  { name: "MIOGLOBINURIA", cost: 50.0 },
  { name: "MONO - TEST", cost: 28.88 },
  { name: "MUTACION JANUS KINASA 2(JAK2)", cost: 648.75 },
  { name: "MYCOPLASMA IGG", cost: 92.95 },
  { name: "MYCOPLASMA IGM", cost: 30.32 },
  { name: "NITROGENO UREICO EN ORINA", cost: 7.22 },
  { name: "NITROGENO UREICO ORINA 24HORAS", cost: 7.22 },
  { name: "OSMOLARIDAD EN ORINA", cost: 33.75 },
  { name: "OXALATOS -ACIDO OXALICO- EN ORINA DE 24 HORAS", cost: 28.8 },
  { name: "OXCARBAZEPINA Y 10-HIDROXICARBAZEPINA SUERO", cost: 56.4 },
  { name: "PANEL 7 ALERGIA ESPECIAL", cost: 130.0 },
  { name: "PANEL 7 ALERGIAS COMIDA", cost: 130.0 },
  { name: "PANEL ALERGIAS COMIDA 3", cost: 162.5 },
  { name: "PANEL GASTROINTESTINAL POR PCR", cost: 480.0 },
  { name: "PAPERAS ANTICUERPOS IGG", cost: 16.49 },
  { name: "PARATHORMONA (INTACTA)", cost: 42.64 },
  { name: "PARVOVIRUS B19 :IGG-IGM", cost: 124.06 },
  { name: "PCR VIRUELA SIMICA", cost: 85.0 },
  { name: "PEPTIDO C", cost: 51.87 },
  { name: "PH EN HECES", cost: 2.92 },
  { name: "PLOMO EN SANGRE TOTAL", cost: 21.6 },
  { name: "PMN", cost: 2.92 },
  { name: "POLISOMNOGRAFIA", cost: 397.07 },
  { name: "POTASIO EN ORINA", cost: 16.11 },
  { name: "POTASIO EN ORINA DE 24 HORAS", cost: 16.11 },
  { name: "PREALBUMINA", cost: 35.0 },
  { name: "PRO-BNP", cost: 75.0 },
  { name: "PROCALCITONINA", cost: 65.56 },
  { name: "PROGESTERONA", cost: 17.79 },
  { name: "PROLACTINA", cost: 17.17 },
  { name: "PROTEINA 2 DE UNION AL FACTOR DE CRECIMIENTO SIMILIAR A LA INSULINA (IGFBP2)", cost: 39.33 },
  { name: "PROTEINA C", cost: 66.4 },
  { name: "PROTEINA S", cost: 80.0 },
  { name: "PROTEINAS DE BENCE JONES", cost: 4.42 },
  { name: "PROTEINAS EN ORINA", cost: 8.24 },
  { name: "PROTEINAS EN ORINA DE 24HORAS", cost: 8.24 },
  { name: "PROTEINAS TOTALES ALBUMINA", cost: 11.93 },
  { name: "PRUEBA DE EMBARAZO", cost: 16.16 },
  { name: "PSA LIBRE Y TOTAL", cost: 49.83 },
  { name: "PSA TOTAL", cost: 30.62 },
  { name: "PUESTA DE YESO ESPECIAL", cost: 64.35 },
  { name: "PUESTA INYECCION INTRAMUSCULAR", cost: 5.0 },
  { name: "PUESTA INYECCION INTRAVENOSA", cost: 5.0 },
  { name: "QUANTIFERON-TB", cost: 120.0 },
  { name: "RECTOSIGMOIDOSCOPIA", cost: 290.0 },
  { name: "RECUENTO DE PLAQUETAS", cost: 6.05 },
  { name: "RENINA ACTIVIDAD PLASMATICA", cost: 27.6 },
  { name: "RETIRO 5 PUNTOS Y MENOS", cost: 7.15 },
  { name: "RETIRO DE 11 PUNTOS Y MAS", cost: 21.24 },
  { name: "RETIRO DE DISPOSITIVOS ANTICONCEPTIVOS", cost: 30.0 },
  { name: "RETIRO DE PUNTOS DE 6 A 10", cost: 13.91 },
  { name: "RETIRO YESO", cost: 15.6 },
  { name: "REVISION DE PLACAS HEMATOLOGICAS", cost: 33.92 },
  { name: "RMN ABD.COMP.Y PELVIS SIMP+CON", cost: 840.34 },
  { name: "RMN ABD.COMPLETO Y PELVIS SIMP", cost: 436.97 },
  { name: "RMN ABDOMEN SUPERIOR SIMP+CON", cost: 420.17 },
  { name: "RMN ABDOMEN SUPERIOR SIMPLE", cost: 210.09 },
  { name: "RMN ANTEBRAZO SIMPLE", cost: 210.09 },
  { name: "RMN ANTEBRAZO SIMPLE +CONTRASTE", cost: 420.17 },
  { name: "RMN BRAZO SIMPLE", cost: 210.09 },
  { name: "RMN BRAZO SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN CADERA SIMPLE", cost: 210.09 },
  { name: "RMN CADERA SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN CODO SIMPLE", cost: 210.09 },
  { name: "RMN CODO SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN COL.LUMBO-SACRA SIMP+CONTR", cost: 420.17 },
  { name: "RMN COL.LUMBO-SACRA SIMPLE", cost: 210.09 },
  { name: "RMN COLUMNA CERVICAL SIMP+CONT", cost: 420.17 },
  { name: "RMN COLUMNA CERVICAL SIMPLE", cost: 210.09 },
  { name: "RMN COLUMNA DORSAL SIMP+CONTR", cost: 420.17 },
  { name: "RMN COLUMNA DORSAL SIMPLE", cost: 210.09 },
  { name: "RMN CUELLO SIMP+CONTR", cost: 420.17 },
  { name: "RMN CUELLO SIMPLE", cost: 210.09 },
  { name: "RMN DE CEREBRO SIMP+CONTR", cost: 420.17 },
  { name: "RMN DE CEREBRO SIMPLE", cost: 301.17 },
  { name: "RMN DE GLUTEO SIMPLE", cost: 210.09 },
  { name: "RMN DE GLUTEO SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN DE MAMAS SIMPLE", cost: 216.0 },
  { name: "RMN DE OIDOS SIMP+CONTR", cost: 420.17 },
  { name: "RMN DE OIDOS SIMPLE", cost: 210.09 },
  { name: "RMN DE ORBITAS SIMP+CONTR", cost: 420.17 },
  { name: "RMN DE ORBITAS SIMPLE", cost: 210.09 },
  { name: "RMN DE PROSTATA SIMPLE", cost: 210.09 },
  { name: "RMN DE PROSTATA SIMPLE+CONSTRATE /MULTIPARAMETRICA", cost: 420.17 },
  { name: "RMN DE VIAS BILIARES /COLANGIORESONANCIA", cost: 309.0 },
  { name: "RMN DE VIAS BILIARES SIMPLE + CONTRASTADA/COLONANGIORESONANCIA", cost: 420.17 },
  { name: "RMN HOMBRO SIMPLE", cost: 210.09 },
  { name: "RMN HOMBRO SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN LARINGE SIMP+CONTR", cost: 420.17 },
  { name: "RMN LARINGE SIMPLE", cost: 210.09 },
  { name: "RMN MAMAS SIMPLE + CONTRASTE", cost: 420.17 },
  { name: "RMN MANO SIMPLE", cost: 210.09 },
  { name: "RMN MANO SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN MU\u00d1ECA SIMPLE", cost: 210.09 },
  { name: "RMN MU\u00d1ECA SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN MUSLO SIMPLE", cost: 210.09 },
  { name: "RMN MUSLO SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN PELVICA SIMP+CONTR", cost: 420.17 },
  { name: "RMN PELVICA SIMPLE", cost: 210.09 },
  { name: "RMN PIE SIMPLE", cost: 210.09 },
  { name: "RMN PIE SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN PIERNA SIMPLE", cost: 210.09 },
  { name: "RMN PIERNA SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN PLEXO BRAQUIAL SIMP+CONTR", cost: 420.17 },
  { name: "RMN PLEXO BRAQUIAL SIMPLE", cost: 210.09 },
  { name: "RMN PLEXO LUMBAR SIMPLE", cost: 210.09 },
  { name: "RMN PLEXO LUMBAR SIMPLE Y CONTRASTADO", cost: 420.17 },
  { name: "RMN RODILLA SIMPLE", cost: 211.0 },
  { name: "RMN RODILLA SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN S.P.N. O CARA SIMP+CONTR", cost: 420.17 },
  { name: "RMN S.P.N. O CARA SIMPLE", cost: 210.09 },
  { name: "RMN SILLA TURCA SIMPLE", cost: 200.79 },
  { name: "RMN TOBILLO SIMPLE", cost: 210.09 },
  { name: "RMN TOBILLO SIMPLE+CONTRASTE", cost: 420.17 },
  { name: "RMN TORAX SIMPLE", cost: 210.09 },
  { name: "RMN TORAX SIMPLE+CONTRASTADA", cost: 420.17 },
  { name: "RMN UNA ARTICULACION SIMP+CON", cost: 420.17 },
  { name: "RMN UNA ARTICULACION SIMPL", cost: 210.09 },
  { name: "ROTAVIRUS", cost: 23.87 },
  { name: "RUBEOLA IGG", cost: 31.37 },
  { name: "RUBEOLA IGM", cost: 39.48 },
  { name: "RX ABDOMEN 1 POSICION", cost: 40.86 },
  { name: "RX ABDOMEN 2 POSICIONES", cost: 48.83 },
  { name: "RX ANTEBRAZO AP Y LATERAL", cost: 48.83 },
  { name: "RX BRAZO AP Y LATERAL", cost: 53.74 },
  { name: "RX CADERA 2 POSICIONES", cost: 62.5 },
  { name: "RX CADERA 3 POSICIONES", cost: 76.41 },
  { name: "RX CADERA 4 POSICIONES", cost: 92.85 },
  { name: "RX CALCANEO 2 POSICIONES", cost: 50.72 },
  { name: "RX CAVUM SIMPLE", cost: 42.87 },
  { name: "RX CERVICAL AP LATERAL Y OBLICUAS", cost: 61.79 },
  { name: "RX CERVICAL FUNCIONAL", cost: 104.9 },
  { name: "RX CLAVICULA 1 POSC.", cost: 42.4 },
  { name: "RX CODO 3 POSC.", cost: 53.74 },
  { name: "RX CODO AP Y LATERAL", cost: 48.83 },
  { name: "RX COLUMNA 1 POSC.- 1 PLACA", cost: 33.61 },
  { name: "RX COLUMNA 2 POSC.-  2 PLACAS", cost: 48.83 },
  { name: "RX COLUMNA 3 POSC.- 3 PLACAS", cost: 84.92 },
  { name: "RX CRANEO 1 POSICION", cost: 38.79 },
  { name: "RX CRANEO 2 POSICIONES", cost: 46.04 },
  { name: "RX CRANEO 3 POSICIONES", cost: 58.64 },
  { name: "RX CUELLO 2 POSC. PARTES BLANDAS", cost: 47.89 },
  { name: "RX DEDOS AP Y LATERAL", cost: 48.12 },
  { name: "RX DORSAL 4 POSICIONES", cost: 76.06 },
  { name: "RX DORSAL AP Y LATERAL", cost: 62.5 },
  { name: "RX EDAD OSEA 1 PLACA", cost: 30.04 },
  { name: "RX EDAD OSEA 2 PLACAS", cost: 52.47 },
  { name: "RX HOMBRO 1 POSICION", cost: 33.61 },
  { name: "RX HOMBRO 2 POSICIONES", cost: 47.89 },
  { name: "RX HOMBRO 3 POSICIONES", cost: 70.78 },
  { name: "RX HOMBRO BILATERAL 1 PLACA", cost: 52.47 },
  { name: "RX HUESOS FACIALES 1 POSICION", cost: 42.87 },
  { name: "RX HUESOS FACIALES 2 POSICIONES", cost: 48.12 },
  { name: "RX HUESOS FACIALES 3 POSICIONES", cost: 53.74 },
  { name: "RX HUESOS NASALES 3 POSC.", cost: 53.74 },
  { name: "RX LUMBAR 4 POSICIONES", cost: 76.06 },
  { name: "RX LUMBAR AP Y LATERAL", cost: 62.5 },
  { name: "RX MANO 2 POSICIONES", cost: 46.04 },
  { name: "RX MAXILAR 2 POSICIONES", cost: 44.07 },
  { name: "RX MIEMBRO INFERIOR 1 POSC.", cost: 38.79 },
  { name: "RX MUNECA 2 POSC.", cost: 46.04 },
  { name: "RX MUNECA 3 POSC.", cost: 53.74 },
  { name: "RX MUSLO AP LATERAL", cost: 62.5 },
  { name: "RX PELVIS 1 POSICION", cost: 30.04 },
  { name: "RX PIE 2 POSICIONES", cost: 48.83 },
  { name: "RX PIE 3 POSC.", cost: 53.74 },
  { name: "RX PIERNA AP Y LATERAL", cost: 48.83 },
  { name: "RX RODILLA 4 POSC.", cost: 80.85 },
  { name: "RX RODILLA AP Y LATERAL", cost: 46.04 },
  { name: "RX SACRO Y COXIS AP - LAT", cost: 47.89 },
  { name: "RX SENOS PARANASALES", cost: 53.38 },
  { name: "RX SILLA TURCA - ESTUDIO", cost: 42.87 },
  { name: "RX TOBILLO 4 POSC.", cost: 63.54 },
  { name: "RX TOBILLO AP Y LATERAL", cost: 48.83 },
  { name: "RX TORAX 1 POSICION", cost: 33.61 },
  { name: "RX TORAX 2 POSICIONES", cost: 48.83 },
  { name: "RX TORAX 3 POSICIONES", cost: 83.53 },
  { name: "RX TORAX OSEO", cost: 83.53 },
  { name: "SANGRE OCULTA", cost: 3.5 },
  { name: "SCREENING X10 DROGAS", cost: 68.53 },
  { name: "SEDIMENTACION", cost: 4.12 },
  { name: "SEROTONINA (5-HIDROXITRIPTAMINA)", cost: 42.0 },
  { name: "SERVICIO LABORATORIO A DOMICILIO", cost: 3.99 },
  { name: "SERVICIO PROCEDIMIENTOS A DOMICILIO", cost: 10.0 },
  { name: "SOBRECARGA GLUCOSA EMBARAZO -50GR", cost: 12.27 },
  { name: "SODIO EN ORINA", cost: 16.11 },
  { name: "SODIO EN ORINA DE 24 HORAS", cost: 16.11 },
  { name: "SUTURA H. DE 11 PUNTOS Y MAS", cost: 45.34 },
  { name: "SUTURA HERIDA 6-10 PUNTOS", cost: 35.57 },
  { name: "SUTURA HERIDA MENOS DE 5 PUNT", cost: 24.84 },
  { name: "T3 TOTAL", cost: 12.4 },
  { name: "T4 TOTAL", cost: 12.4 },
  { name: "TAC ABDOMEN -3D", cost: 214.29 },
  { name: "TAC ABDOMEN SIMPLE", cost: 119.05 },
  { name: "TAC ABDOMEN SIMPLE + CONTRASTE IV", cost: 201.3 },
  { name: "TAC ABDOMEN SIMPLE + CONTRASTE ORAL", cost: 136.51 },
  { name: "TAC ABDOMEN SIMPLE + CONTRASTE ORAL+IV", cost: 240.17 },
  { name: "TAC ANTEBRAZO SIMPLE", cost: 100.0 },
  { name: "TAC ANTEBRAZO SIMPLE+CONTRASTE IV", cost: 203.17 },
  { name: "TAC ARTICULACION SIMPLE Y CONTRASTADA", cost: 217.46 },
  { name: "TAC BRAZO SIMPLE", cost: 103.17 },
  { name: "TAC BRAZO SIMPLE+CONTRASTE IV", cost: 203.17 },
  { name: "TAC CADERA SIMPLE", cost: 103.17 },
  { name: "TAC CADERA SIMPLE+CONTRASTE IV", cost: 203.17 },
  { name: "TAC CARA - 3D", cost: 219.05 },
  { name: "TAC CARA SIMPLE + CONTRASTE IV", cost: 201.3 },
  { name: "TAC CERVICAL", cost: 114.0 },
  { name: "TAC CODO SIMPLE", cost: 100.0 },
  { name: "TAC CODO SIMPLE+CONTRASTE IV", cost: 203.17 },
  { name: "TAC COLUMNA OSEA 3 VERTEBRAS - 3D", cost: 219.05 },
  { name: "TAC CONDUCTO AUDIT.SIMPLE+CONTR IV", cost: 191.56 },
  { name: "TAC CONDUCTO AUDITIVO SIMPLE", cost: 108.7 },
  { name: "TAC CRANEO - 3D", cost: 219.05 },
  { name: "TAC CRANEO SIMPLE", cost: 96.83 },
  { name: "TAC CRANEO SIMPLE +CONTRASTE IV", cost: 202.92 },
  { name: "TAC CUELLO - 3D", cost: 128.57 },
  { name: "TAC CUELLO SIMPLE", cost: 103.17 },
  { name: "TAC CUELLO SIMPLE + CONTRASTE IV", cost: 190.0 },
  { name: "TAC DE CARA SIMPLE", cost: 108.7 },
  { name: "TAC DE PELVIS SIMPLE", cost: 114.0 },
  { name: "TAC DE SPN.", cost: 92.98 },
  { name: "TAC DORSAL", cost: 114.0 },
  { name: "TAC ESCANOGRAMA", cost: 87.3 },
  { name: "TAC HOMBRO SIMPLE", cost: 106.88 },
  { name: "TAC HOMBRO SIMPLE+CONTRASTE IV", cost: 203.17 },
  { name: "TAC LUMBAR", cost: 114.0 },
  { name: "TAC LUMBAR SIMPLE Y CONTRASTADA", cost: 220.63 },
  { name: "TAC MANO SIMPLE", cost: 100.0 },
  { name: "TAC MANO SIMPLE+CONTRASTE IV", cost: 615.95 },
  { name: "TAC MU\u00d1ECA SIMPLE", cost: 93.65 },
  { name: "TAC MU\u00d1ECA SIMPLE+CONTRASTE IV", cost: 203.17 },
  { name: "TAC MUSLO SIMPLE", cost: 103.17 },
  { name: "TAC MUSLO SIMPLE+CONTRASTE IV", cost: 203.17 },
  { name: "TAC ORBITAS SIMPLE", cost: 104.76 },
  { name: "TAC ORBITAS SIMPLE + CONTRASTE IV", cost: 193.18 },
  { name: "TAC PELVIS - 3D", cost: 270.43 },
  { name: "TAC PELVIS ABD. SIMPLE+CONTR. ORAL", cost: 190.48 },
  { name: "TAC PELVIS ABD.SIMPLE +CONTRASTE IV", cost: 296.88 },
  { name: "TAC PELVIS SIMPLE + CONTR. IV.", cost: 144.79 },
  { name: "TAC PELVIS Y ABD. SIMPLE", cost: 252.1 },
  { name: "TAC PIE SIMPLE", cost: 100.0 },
  { name: "TAC PIE SIMPLE+CONTRASTE IV", cost: 203.17 },
  { name: "TAC PIERNA SIMPLE", cost: 100.0 },
  { name: "TAC PIERNA SIMPLE+CONTRASTE IV", cost: 203.17 },
  { name: "TAC RODILLA SIMPLE", cost: 100.0 },
  { name: "TAC RODILLA SIMPLE+CONTRASTE IV", cost: 203.17 },
  { name: "TAC SILLA TURCA S/C. IV.", cost: 188.31 },
  { name: "TAC SILLA TURCA SIMPLE", cost: 103.17 },
  { name: "TAC TOBILLO SIMPLE", cost: 106.88 },
  { name: "TAC TOBILLO SIMPLE+CONTRASTE IV", cost: 203.17 },
  { name: "TAC TORAX - 3D", cost: 270.43 },
  { name: "TAC TORAX SIMPLE", cost: 107.94 },
  { name: "TAC TORAX SIMPLE + CONTRASTE IV", cost: 226.89 },
  { name: "TAC UN ESPACIO INTERVERTEBRAL - 3D", cost: 125.0 },
  { name: "TAC UNA ARTICULACION - 3D", cost: 219.05 },
  { name: "TAC UNA ARTICULACION SIMPLE", cost: 101.59 },
  { name: "TAC UNION CRANEO CERVICAL - 3D", cost: 219.05 },
  { name: "TAC UNION CRANEO CERVICAL S. CONTS", cost: 133.12 },
  { name: "TAC UNION CRANEO CERVICAL SIMPLE", cost: 106.35 },
  { name: "TESTOSTERONA LIBRE", cost: 16.8 },
  { name: "TESTOSTERONA TOTAL", cost: 18.76 },
  { name: "TIEMPO DE COAGULACION", cost: 4.67 },
  { name: "TIEMPO DE HEMORRAGIA", cost: 15.69 },
  { name: "TIEMPO DE PROTROMBINA - TP", cost: 5.61 },
  { name: "TIEMPO DE TROMBINA -TT", cost: 18.96 },
  { name: "TIEMPO DE TROMBOPLASTINA -TTP", cost: 4.84 },
  { name: "TIMPANOMETRIA", cost: 32.14 },
  { name: "TIPIFICACION SANGUINEA", cost: 18.77 },
  { name: "TIROGLOBULINA", cost: 51.27 },
  { name: "TNF", cost: 100.92 },
  { name: "TOMA DE PRESION ARTERIAL", cost: 2.86 },
  { name: "TORCH IGG", cost: 107.15 },
  { name: "TORCH IGM", cost: 115.32 },
  { name: "TORCH TOTAL", cost: 282.75 },
  { name: "TOXINA CLOSTRIDIUM DIFICILE", cost: 96.82 },
  { name: "TOXOPLASMA IGA", cost: 44.99 },
  { name: "TOXOPLASMA IGG", cost: 33.92 },
  { name: "TOXOPLASMA IGG-AVIDEZ", cost: 53.76 },
  { name: "TOXOPLASMA IGM", cost: 43.27 },
  { name: "TP DE CONTROL", cost: 4.22 },
  { name: "TRANSFERRINA", cost: 12.85 },
  { name: "TRATAMIENTO QUEMADURA I-II 15%", cost: 25.0 },
  { name: "TRATAMIENTO QUEMADURA I-II 30%", cost: 30.0 },
  { name: "TREPONEMA PALLIDUM IGG", cost: 43.71 },
  { name: "TREPONEMA PALLIDUM IGM", cost: 43.71 },
  { name: "TRIGLICERIDOS", cost: 8.58 },
  { name: "TROPONINA T ULTRASENSIBLE", cost: 41.9 },
  { name: "TSH", cost: 10.29 },
  { name: "TUBERCULOSIS POR ADN-PCR", cost: 130.0 },
  { name: "UREA", cost: 7.22 },
  { name: "URO TAC SIMPLE", cost: 164.29 },
  { name: "URO TAC SIMPLE Y CONTRASTADA", cost: 353.57 },
  { name: "V.D.R.L.", cost: 5.38 },
  { name: "VALORACION OPTOMETRICA", cost: 12.0 },
  { name: "VARICELA ZOSTER IGG", cost: 52.92 },
  { name: "VARICELA ZOSTER IGM", cost: 52.92 },
  { name: "VENDAJE DE YESO CON FIBRA VIDRIO DE MUSLO A DEDOS PIE", cost: 30.32 },
  { name: "VISCOSUPLEMENTACION", cost: 51.42 },
  { name: "VITAMINA B 12", cost: 40.18 },
  { name: "VITAMINA D 25 HIDROXI TOTAL", cost: 55.9 },
  { name: "VULVOSCOPIA + TOMA DE MUESTRA", cost: 80.0 },
  { name: "ZIEHL POR 1 MUESTRA", cost: 4.12 },
  { name: "ZINC SUERO / PLASMA", cost: 38.4 },
  { name: "CULTIVO DE ORINA", cost: 23.38 }
];
